# Generated by Django 4.1.4 on 2022-12-14 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCompetence', models.CharField(max_length=25)),
                ('niveauCompetence', models.IntegerField()),
                ('genre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomGenre', models.TextField()),
                ('descriptionGenre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureStage', models.CharField(max_length=20)),
                ('lieuStage', models.CharField(max_length=20)),
                ('dureeStage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDiplome', models.CharField(max_length=25)),
                ('lieuDiplome', models.CharField(max_length=25)),
                ('dateDiplome', models.DateField()),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.genre')),
            ],
        ),
    ]
